export const excelMainList = [
  { id: 1, name: "Employee", value: "employeeRole" },
  { id: 2, name: "Courses", value: "course" },
  { id: 3, name: "Empl Evaluation", value: "employeeEvaluation" },
];

export const skillMaximumScoreValue = 3;

export const mainCategory = [
  { id: 1, name: "Data Analytics", value: "data_analytics" },
  { id: 2, name: "Cyber Security", value: "cyber_security" },
  { id: 3, name: "ICT", value: "ict" },
];
export const mainEntity = [
  { id: 1, label: "DEWA", value: "dewa", logo: "dewa.jpeg" },
  {
    id: 2,
    label: "Dubai Municipality",
    value: "dubai_municipality",
    logo: "dubai-municipality.jpeg",
  },
  { id: 3, label: "Dubai DET", value: "dubai_det", logo: "det.png" },

  {
    id: 4,
    label: "Department of finance dubai",
    value: "dept_of_finance_dubai",
    logo: "dof.jpeg",
  },
  {
    id: 5,
    label: "Dubai digital authority",
    value: "dept_of_finance_dubai",
    logo: "digital-dubai.png",
  },
  {
    id: 7,
    label: "Department of Economic Development",
    value: "dept_of_economic_development",
    logo: "ded.jpeg",
  },
  {
    id: 8,
    label: "Dubai Chamber",
    value: "dubai_chamber",
    logo: "dubai-chamber.png",
  },
  {
    id: 9,
    label: "Dubai customs",
    value: "dubai_customs",
    logo: "dubai-customs.png",
  },
  {
    id: 10,
    label: "Duai Police",
    value: "dubai_police",
    logo: "dubai-police.png",
  },
  {
    id: 11,
    label: "Community Development Authority",
    value: "community_dev_authority",
    logo: "cda.png",
  },
  {
    id: 12,
    label: "DEWA",
    value: "community_dev_authority",
    logo: "dewa.jpeg",
  },
  {
    id: 13,
    label: "UAE University",
    value: "uae university",
    logo: "uaeu.png",
  },
];

export const chartDetails = {
  data_analytics: {
    id: 1,
    name: "Data Analytics",
    value: "data_analytics",
    total_employees: 40,
  },
  cyber_security: {
    id: 2,
    name: "Cyber Security",
    value: "cyber_security",
    total_employees: 86,
  },
  ict: { id: 3, name: "ICT", value: "ict", total_employees: 58 },
};

export const allEmployeeDetails = [
  {
    employee_number: 0,
    entity: "Dubai Chamber",
    job: "Specialist",
    category: "",
    sub_category: "",
    role: "",
    technical_skills: [
      {
        name: "Information Security",
        score: 1,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "ISR", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Audit and Compliance",
        score: 1,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Risk Management", score: 3, achievedStatus: 1, highestValue: 3 },
      { name: "Report Writing ", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Security Governance",
        score: 1,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Strategy Planning",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Development of Policies, Procedures and Strategy",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Communication", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Analytical Thinking",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Teamwork", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
    ],
    evaluation_result: "Problem solving",
    soft_skills: "",
    evaluation_date: null,
  },
  {
    employee_number: 1111,
    entity: "DEWA",
    job: "Acting Head Of Office",
    category: "Cyber security",
    sub_category: "Cybersecurity Governance",
    role: "Senior IS GRC Leader (CISO)",
    technical_skills: [
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "ISR", score: 3, achievedStatus: 1, highestValue: 3 },
      ,
      {
        name: "Audit and Compliance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      ,
      { name: "Risk Management", score: 3, achievedStatus: 1, highestValue: 3 },
      { name: "Report Writing ", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Security Governance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Strategy Planning",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Development of Policies, Procedures and Strategy",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Communication", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Analytical Thinking",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Teamwork", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
    ],
    evaluation_result: "•Information Security",
    soft_skills: "",
    evaluation_date: null,
  },
  {
    employee_number: 1156,
    entity: "Dubai digital authority",
    job: "Acting Head Of Office",
    category: "Cyber security",
    sub_category: "Cybersecurity Governance",
    role: "Senior IS GRC Leader (CISO)",
    technical_skills: [
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 0,
        highestValue: 3,
      },
      { name: "ISR", score: 2, achievedStatus: 1, highestValue: 3 },
      {
        name: "Audit and Compliance",
        score: 2,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Risk Management", score: 1, achievedStatus: 1, highestValue: 3 },
      { name: "Report Writing ", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Security Governance",
        score: 2,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Strategy Planning",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Development of Policies, Procedures and Strategy",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Communication", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Analytical Thinking",
        score: 2,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Teamwork", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
    ],
    evaluation_result: "•Information Security",
    soft_skills: "",
    evaluation_date: null,
  },
  {
    employee_number: 1122,
    entity: "Dubai digital authority",
    job: "Acting Head Of Office",
    category: "Data Analysis",
    sub_category: "Cybersecurity Governance",
    role: "Senior IS GRC Leader (CISO)",
    technical_skills: [
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 0,
        highestValue: 3,
      },
      { name: "ISR", score: 2, achievedStatus: 1, highestValue: 3 },
      {
        name: "Audit and Compliance",
        score: 2,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Risk Management", score: 1, achievedStatus: 1, highestValue: 3 },
      { name: "Report Writing ", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Security Governance",
        score: 2,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Strategy Planning",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Development of Policies, Procedures and Strategy",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Communication", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Analytical Thinking",
        score: 2,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Teamwork", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
    ],
    evaluation_result: "•Information Security",
    soft_skills: "",
    evaluation_date: null,
  },
  {
    employee_number: 1158,
    entity: "Dubai digital authority",
    job: "Acting Head Of Office",
    category: "ICT",
    sub_category: "Cybersecurity Governance",
    role: "Senior IS GRC Leader (CISO)",
    technical_skills: [
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 0,
        highestValue: 3,
      },
      { name: "ISR", score: 2, achievedStatus: 1, highestValue: 3 },
      {
        name: "Audit and Compliance",
        score: 2,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Risk Management", score: 1, achievedStatus: 1, highestValue: 3 },
      { name: "Report Writing ", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Security Governance",
        score: 2,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Strategy Planning",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Development of Policies, Procedures and Strategy",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Communication", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Analytical Thinking",
        score: 2,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Teamwork", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
    ],
    evaluation_result: "•Information Security",
    soft_skills: "",
    evaluation_date: null,
  },
  {
    employee_number: 2211,
    entity: "Dubai digital authority",
    job: "Specialist",
    category: "ICT",
    sub_category: "Infrastructure ",
    role: "Application Specialist",
    technical_skills: [
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "ISR", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Audit and Compliance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Risk Management", score: 3, achievedStatus: 1, highestValue: 3 },
      { name: "Report Writing ", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Security Governance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Strategy Planning",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Development of Policies, Procedures and Strategy",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Communication", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Analytical Thinking",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Teamwork", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
    ],
    evaluation_result: "•Business Risk Management ",
    soft_skills: "",
    evaluation_date: null,
  },
  {
    employee_number: 2222,
    entity: "Dubai Municipality",
    job: "Specialist",
    category: "ICT",
    sub_category: "Infrastructure ",
    role: "Application Specialist",
    technical_skills: [
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "ISR", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Audit and Compliance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Risk Management", score: 3, achievedStatus: 1, highestValue: 3 },
      { name: "Report Writing ", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Security Governance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Strategy Planning",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Development of Policies, Procedures and Strategy",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Communication", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Analytical Thinking",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Teamwork", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
    ],
    evaluation_result: "•Business Risk Management ",
    soft_skills: "",
    evaluation_date: null,
  },
  {
    employee_number: 2276,
    entity: "Dubai Municipality",
    job: "Specialist",
    category: "data analytics",
    sub_category: "Infrastructure ",
    role: "Application Specialist",
    technical_skills: [
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "ISR", score: 3, achievedStatus: 1, highestValue: 3 },
      ,
      {
        name: "Audit and Compliance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Risk Management", score: 3, achievedStatus: 1, highestValue: 3 },
      { name: "Report Writing ", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Security Governance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Strategy Planning",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Development of Policies, Procedures and Strategy",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Communication", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Analytical Thinking",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Teamwork", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
    ],
    evaluation_result: "•Business Risk Management ",
    soft_skills: "",
    evaluation_date: null,
  },
  {
    employee_number: 2278,
    entity: "Dubai customs",
    job: "Specialist",
    category: "ICT",
    sub_category: "Infrastructure ",
    role: "Application Specialist",
    technical_skills: [
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "ISR", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Audit and Compliance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Risk Management", score: 3, achievedStatus: 1, highestValue: 3 },
      { name: "Report Writing ", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Security Governance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Strategy Planning",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Development of Policies, Procedures and Strategy",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Communication", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Analytical Thinking",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Teamwork", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
    ],
    evaluation_result: "•Business Risk Management ",
    soft_skills: "",
    evaluation_date: null,
  },
  {
    employee_number: 2762,
    entity: "Dubai customs",
    job: "Specialist",
    category: "data analytics",
    sub_category: "Infrastructure ",
    role: "Application Specialist",
    technical_skills: [
      {
        name: "Information Security",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "ISR", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Audit and Compliance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Risk Management", score: 3, achievedStatus: 1, highestValue: 3 },
      { name: "Report Writing ", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Security Governance",
        score: 3,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Strategy Planning",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Development of Policies, Procedures and Strategy",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Communication", score: 0, achievedStatus: 1, highestValue: 3 },
      {
        name: "Analytical Thinking",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      { name: "Teamwork", score: 3, achievedStatus: 1, highestValue: 3 },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
      {
        name: "Information Security",
        score: 0,
        achievedStatus: 1,
        highestValue: 3,
      },
    ],
    evaluation_result: "•Business Risk Management ",
    soft_skills: "",
    evaluation_date: null,
  },
];
